name: webflow_client
description: Webflow API v2 client for dart and flutter, uses light weight http package to make requests.
version: 0.1.7
repository: https://github.com/YoussefEgla/webflow_dart_client

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  http: ^1.2.1
  json_annotation: ^4.9.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  build_runner: ^2.3.3
  json_serializable: ^6.1.5
